### ISSUE TITLE
Naming of OAuth1 vs OAuth2 classes and methods

### ISSUE THREAD

**Issue by mnivet** [MitjaBezensek/SharpBucket#102]
We have multiple classes and methods which name is not obvious to distinct OAuth1 vs OAuth2

In particular the following classes:
* `OAuthentication2Legged` and `OAuthentication3Legged` which are OAuth1
* `OAuthentication2` which is OAuth2

And the corresponding methods in `SharpBucket` class:
* `OAuth2LeggedAuthentication` and `OAuth3LeggedAuthentication` which are OAuth1
* `OAuthentication2` which is OAuth2

The issue comes from the fact that "OAuth 2 legged" is clearly not "Oauth2 legged", but when all is join in a method name its become hard to distinct both.
Can we try to deprecate that methods and classes for methods with more explicit naming ?

My suggestion would be to harmonize the classes and methods names to be the same, and named like that:
`OAuth2LeggedAuthentication` => `OAuthWith2LeggedAuthentication`
`OAuth3LeggedAuthentication` => `OAuthWith3LeggedAuthentication`
`OAuthentication2` => `OAuth2WithClientCredentialsGrant` (because it's named like that here : https://developer.atlassian.com/bitbucket/api/2/reference/meta/authentication, and it will let us the door open to implements others OAuth2 scenarios like the *"Resource Owner Password Credentials Grant"* which is probably an improvement of the `BasicAuthentication` that we already have)

**Comment by asherber** [comment]
I would go with something more like:

```
OAuth1TwoLeggedAuthentication
OAuth1ThreeLeggedAuthentication
OAuth2ClientCredentials
```

**Comment by mnivet** [comment]
Your suggestion seem better than mine

Writing the numbers of the authentication style with letters provide a clearer distinction with the number of the protocol version and allow to remove the `With` keyword that was present in my proposition, which in definitive produce names that are more simple to read. 😄 

I'll try to do that now
