### ISSUE TITLE
OAuthentication2 problem

### ISSUE THREAD

**Issue by andySF** [MitjaBezensek/SharpBucket#105]
```
var sharpBucket = new SharpBucketV2();
sharpBucket.OAuthentication2(Key,Secret)
```
throws 
>System.Exception: 'Unable to retrieve OAuth2 Token:
0
'

Any help? Thanks.

**Comment by andySF** [comment]
After reading the manual, I was using the wrong key and Secrete. I just learned that I need to use via  https://developer.atlassian.com/apps/

**Comment by mnivet** [comment]
Your OAuth consumer should have a callback URL to allow OAuth2.0
like on that screenshot : https://github.com/MitjaBezensek/SharpBucket/blob/master/Assets/OauthConsumerConfig.png

it's written under the field *"required for OAuth2"*
Even if it's not used in the HTTP exchanged, it seems to be like a sort of strange feature flipping in bitbucket...
