### ISSUE TITLE
Lacking an endpoint to fetch activity from ONE pull request

### ISSUE THREAD

**Issue by johnnyasantoss** [MitjaBezensek/SharpBucket#110]
Hello, I would like to know if this endpoint is already covered OR if there's a way to do a custom endpoint call using this lib.
More specifically this [endpoint][endpoint] which is not listed on `Coverage.md`

 [endpoint]: https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/pullrequests/%7Bpull_request_id%7D/activity

**Comment by mnivet** [comment]
I've just search the word `activity` in [coverage.md](https://github.com/MitjaBezensek/SharpBucket/blob/master/Coverage.md) and found this endpoint

It says that it is implemented by `PullRequestResource.GetPullRequestActivity()` and covered by unit tests so yes you can call this endpoint using this lib

here a micro code sample that should help you to use that lib to perform that call
```CSharp
            var sharpBucket = new SharpBucketV2();
            sharpBucket.NoAuthentication(); // choose the appropriate authentication method instead of that
            sharpBucket.RepositoriesEndPoint()
                .RepositoryResource("account", "repoName")
                .PullRequestsResource()
                .PullRequestResource(42) // 42 = a pull request id
                .GetPullRequestActivity();
```
