### ISSUE TITLE
Commit filtering?

### ISSUE THREAD

**Issue by coridrew** [MitjaBezensek/SharpBucket#114]
I can't find a way to filter commits using SharpBucket like I can with a direct call in the api: 
https://api.bitbucket.org/2.0/repositories/{user}/{slug}/commits/{branch}?exclude=master

Is it possible to append "**?exclude=master**" (for example) to RepositoryResource.ListCommits? 
I don't see a way to use filter or overrideUrl, when listing commits, to acheive this.

**Comment by mnivet** [comment]
Effectively, this is not implemented yet,
We will add this to our backlog to add new overloads to be able to do that

**Comment by mnivet** [comment]
Next release (v0.11.0) will resolve this issue by providing new overloads of the RepositoryResource.ListCommits method that will allow that.
