### ISSUE TITLE
Expose Enumerate... methods in addition to existing List... methods

### ISSUE THREAD

**Issue by mnivet** [MitjaBezensek/SharpBucket#124]
We recently add the [EnumerateSearchCodeSearchResults](https://github.com/MitjaBezensek/SharpBucket/blob/master/SharpBucket/V2/EndPoints/TeamResource.cs#L127) method in TeamResource.
That method allow to enumerate paged values page by page which in multiple cases is mush more efficient than returning a fully fetched list (in particular on big volume of results)

It would be great now to add Enumerate alternatives to all the existing List methods.
Now we have one model, it should not be difficult to do, it just take time to go in all endpoints and resources to add that alternatives.

**Comment by chole22** [comment]
`[]() 

> #`

**Comment by mnivet** [comment]
Works progress well. I've done a search on methods that return List<> and found only two remaining methods that do not have the overloads:

- [ ] ListCommitComments in RepositoryResource
- [ ] ListRepositories in UsersEndpoint

**Comment by mnivet** [comment]
All overloads are now available.
This should now be released in next version (expected to be V0.14)
