### ISSUE TITLE
Improve the testing

### ISSUE THREAD

**Issue by MitjaBezensek** [MitjaBezensek/SharpBucket#13]
The basic testing logic has been added but now we need to write additional tests. For now at least the tests that target the publicly accessible repos. [Here](https://github.com/MitjaBezensek/SharpBucket/blob/master/SharpBucketTests/V2/EndPoints/RepositoryResourceTests.cs) is an example of how they might look like.

Apart from writing additional tests also consider running the tests on the AppVeyor CI. Would need to find a way to set up the authentication info on the AppVeyor project.
- [ ] Write additional tests for the api calls that work on public repos.
- [x] Configure AppVeyor to run the tests, figure out how to deal with authentication - maybe environment variables.
- [x] Figure out the best way to run api calls for private repos (probably each developer should create a private repo just for testing and the testing logic should then keep this repo in a consistent state).
- [ ] Clean up the Console test project when tests will be implemented. It should contain only a very brief, concise, clear guide about how you should use SharpBucket.
- [ ] [Some tests are brittle](https://github.com/MitjaBezensek/SharpBucket/blob/master/SharpBucketTests/V2/EndPoints/TeamsEndPointTests.cs#L27-L32) since they rely on third party accounts. Maybe create a repository on SharpBucket, so that it is under our control and wont change.

**Comment by MitjaBezensek** [comment]
Just checked out AppVeyour and found out that we could probably use environment variables for authentication data. We could maybe switch to using environment variables for the console application program as well.

**Comment by MitjaBezensek** [comment]
Added environment variables for testing. Configured AppVeyor to now also run tests.

**Comment by MitjaBezensek** [comment]
Added another environment variable so that we can [test some authenticated calls](         var accountName = Environment.GetEnvironmentVariable("SB_ACCOUNT_NAME");
) as well:

**Comment by anh-duc-le** [comment]
This part will cause issues if you don't have more than 5 changesets on the repository. 
I think it's a good idea to make mention of this somewhere, because most people (_like me_) will be running this on a brand new testing repository with only one changeset: "Initial commit".
```
private static void TestRepositoriesEndPoint(SharpBucketV1 sharpBucket)
{
    ...
    var changeSet = repositoriesEndPoint.ListChangeset();
    var change = changeSet.changesets[4];
    ...
}
```

**Comment by mnivet** [comment]
Pull request #91 comes with great improvements for unit tests with code that dynamically create and drop a public repository with commit and branches that can be manipulate safely in the unit tests

This should be a good starting point to rewrite brittle tests against data that are totally managed by the tests

There is still a lot of work to do to cover all api calls, but with that pull request and what have already be done on AppVeyor we have the tools to do it.

Furthermore, test coverage progression can now be followed in [Coverage.md](https://github.com/MitjaBezensek/SharpBucket/blob/master/Coverage.md) which means that we don't need that issue any more to follow that.

What remains from that issue after that ? Only the clean up of Console test project no ?
@MitjaBezensek: Do we really need it ? Unit tests are already samples providers, and brief usage description is already in the readme at the root.

**Comment by MitjaBezensek** [comment]
No it's not needed anymore. It only served as a kind of documentation on how to use the library. If it is removed then the Readme should be updated as well since it references the Console project a lot.

**Comment by mnivet** [comment]
I've removed the Console tests project, and changed the documentation to reference the SharpBucketCli project
This is a new program that can also serve as a small sample, but with the objective to help developers to maintain a clean test environment instead of trying to be a test program like the deleted one.

Main objectives of that issues are now fulfilled. So lets close it and reopen new ones more precise if we need.
