### ISSUE TITLE
Clone and Fetch

### ISSUE THREAD

**Issue by unipeg** [MitjaBezensek/SharpBucket#141]
How do I perform a simple Clone or Fetch operation with SharpBucket (if possible?)

**Comment by mnivet** [comment]
No it's not the intend of that library
clone and fetch are git operation, not APIs.
This library can help you to list the tags or commits that exists in a repository stored on BitBucket.
Then you may use that information to clone and checkout a selected tag, using git or potentially a C# implementation of git like [LibGit2Sharp](https://github.com/libgit2/libgit2sharp)

We do that in the unit tests of Sharpbucket if you need an example.
Look here: https://github.com/MitjaBezensek/SharpBucket/blob/master/SharpBucketTests/GitHelpers/TestRepositoryBuilder.cs#L33

The only thing that SharpBucket can provide you is a way to get an OAuth2 token to identify yourself in the git commands, like we do in our unit tests, which could be useful if you do not have access to the credentials of a user or an SSH key to authenticate your git commands.
