### ISSUE TITLE
Enable setting the number of results to retrieve from repositories endpoint

### ISSUE THREAD

**Issue by LSTANCZYK** [MitjaBezensek/SharpBucket#20]
Currently the RepositoriesEndPoint's ListRepositories method does not allow retrieving more than first 10 results - I would like to be able to retrieve more than that.

**Comment by MitjaBezensek** [comment]
I completely agree :+1: 

This was already added in #10 but I did not push the changes to NuGet yet. This addition breaks a few things so I'll check if there are any other improvements / changes I'd like to add with this release. Should be in the next couple of days.

**Comment by Xanvier54** [comment]
Looking forward for this imporovement! :smile:

**Comment by MitjaBezensek** [comment]
I'm sorry this is taking a while. I've been working on it but have found out an issue with the added pagination and authetincation #23. I'll try to fix it as soon as I can.

**Comment by MitjaBezensek** [comment]
The issues that were preventing pagination to be released have been fixed. I have just published version 0.5.0 to Nuget. There are some breaking changes to be aware of:
https://github.com/MitjaBezensek/SharpBucket/releases/tag/0.5.0
