### ISSUE TITLE
OAuth1 does not work for paginated request

### ISSUE THREAD

**Issue by MitjaBezensek** [MitjaBezensek/SharpBucket#23]
The pagination seems to break the OAuth1 authentication. The problem is that the url is just appened to the base url of the resource. For OAuth1 this is problematic since oauth_signature is calculated based on it.

The solution might be quite simple. We should pass a List of parameters to the ```ExecuteRequest``` method which will then just add them as parameters like so: ```request.AddParameter("pagelen", 30);```

I have tested this and it works. @0x1mason are you up for this one since you might be the most familiar with the logic of pagingation?

**Comment by 0x1mason** [comment]
I'll try to take a look at it next week.

**Comment by MitjaBezensek** [comment]
Great :+1:

**Comment by MitjaBezensek** [comment]
Did you maybe start on this? I'll have some time tomorrow and could take this on, but don't want to duplicate the effort :)

**Comment by 0x1mason** [comment]
I'll have time next week. Sorry, been quite busy.

**Comment by 0x1mason** [comment]
However, if you think you can knock it out quickly, then by all means, go
ahead. I'm no longer working at the company that requires this library, so
I won't be contributing as much, unfortunately.

**Comment by MitjaBezensek** [comment]
Yeah, no problem. I have some spare time so I'll tackle it.
