### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by MitjaBezensek** [MitjaBezensek/SharpBucket#24]
- [x] OAuth2 was added
- [x] For testing purposes environment variables need to be set (add contributing info that explains this)
- [ ] Setting the number of results (pagination) was added

**Comment by mlandefeld** [comment]
Hey, I found this on [up for grabs](http://up-for-grabs.net/#/). Is there anything I can do to help out?

**Comment by MitjaBezensek** [comment]
Sorry for a late reply. There are still quite a few things missing. Here is a bit more information about [what exactly](https://github.com/MitjaBezensek/SharpBucket/blob/master/Contribution.md). In terms of documentation, you can see the two items that could be updated. Oauth2 authentication was added, but there is no information on the readme page. The same with using the api with paginated results. There are some examples of pagination in the tests so readme could be updated to show a paginated api call or something along those lines.
