### ISSUE TITLE
Creating a repository using v2 API

### ISSUE THREAD

**Issue by JJCLane** [MitjaBezensek/SharpBucket#25]
I'm struggling to create an issue using the v2 api, is this something that hasn't been implemented yet?

I've created a new repository using the POCO but can't see how it should be posted to the repositories endpoint. 

Thanks!

**Comment by MitjaBezensek** [comment]
I believe the V2 of Bitbucket API is quite limited. Quite a few things don't seem to be implemented at all, issues being one of them.

For example, here is the [repositories endpoint in V1](https://confluence.atlassian.com/bitbucket/repositories-endpoint-1-0-296092719.html), which includes issues resource. However [repositories endpoint in V2](https://confluence.atlassian.com/bitbucket/repositories-endpoint-423626330.html) does not contain issues resource, nor does any [other endpoint](https://confluence.atlassian.com/bitbucket/version-2-423626329.html#Version2-Supportedendpointsandtheirresources). 

Until they add additional resources I'd recommend you to use the V1 of the api for adding issues. Here is a quote from their site:
> Supported Versions
There is a 1.0 and 2.0 version of the APIs. The two versions do not encompass the same endpoints or functionality. Currently, you will find that the API 1.0 covers resources that the 2.0 API is yet to cover. Conversely, the 2.0 API has several features that enhance its usability and performance. You should look first to use the 2.0 API whenever possible. The 1.0 APIs are available when the 2.0 does not make the resource you need available.

**Comment by JJCLane** [comment]
Ah sorry, I accidentally mentioned issue when I was talking about repositories. It does cover the creation of repositories as I have it working using a standard HttpClient but thought it would be good to use this library if possible. The endpoint is https://api.bitbucket.org/2.0/repositories/{owner}/{repo_slug}. I can submit a PR if you let me know your ideal implementation, I was thinking it would make sense to have a .PostRepository() method that would accept the new Repository POCO?

**Comment by MitjaBezensek** [comment]
Yeah, that sounds great.
