### ISSUE TITLE
Unable to set issue.responsible when creating a new Issue? 

### ISSUE THREAD

**Issue by bedirhan** [MitjaBezensek/SharpBucket#31]
Surely I'm missing smt... Using V1.

``` javascript
Issue newIssue = new Issue();
...
newIssue.responsible = new User();
newIssue.responsible.username = bitbucketAssigneeTextBox.Text.Trim();

RepositoriesEndPoint repositoryEndPoint = ConnectToBitbucket();
IssuesResource issuesResource = repositoryEndPoint.IssuesResource();
Issue newlyOpenedIssue = issuesResource.PostIssue(newIssue);
...
```

the code above produces the below POST body which of course Bitbucket doesn't support 

...&priority=major&reported_by=SharpBucket.V1.Pocos.User..

There used to be NewIssue, ExistingIssue POCOs. Or should I implement them myself extending Issue.

**Comment by MitjaBezensek** [comment]
I see, it seems that the objects are not exactly the same for posting and getting the issue. For posting the `reported_by` is just the username string of the user, where for getting it it is a whole POCO object.

I did just a bit of research and see two options:

1. Having two sets of classes like you described. The users of the api would then need to know that there are two different classes and use the correct one for each scenario - use `NewIssue` POCO when posting and `Issue` when getting.

2. We could solve this issue by serializing the objects differently, depending on the type of request (post, get,...). I see that json.net does offer [conditional serialization](http://www.newtonsoft.com/json/help/html/ConditionalProperties.htm) but I'm not sure how / if this would be possible for this case.

Which one do you would work better for your case? Can you look into option 2 if it would be viable for this case? If not I can do it next week.

**Comment by bedirhan** [comment]
I've pursued the second option and created two distinct objects and relevant underlying methods; NewIssue, ExistingIssue. I've also contemplated about the second option, but this one was easier to implement.

**Comment by MitjaBezensek** [comment]
@bedirhan Just checking up on this. I guess you created this in a private repo? Do you think we should do something similar here?

**Comment by mnivet** [comment]
We are planning to drop support of API V1 since Bitbucket as deprecated it and will close access to it
So if nobody says something else here it will be closed soon
