### ISSUE TITLE
Failing to set Auth Tokens > AuthenticatewithPin

### ISSUE THREAD

**Issue by techy2493** [MitjaBezensek/SharpBucket#43]
Failing to authenticate and getting a System.Net.WebException

I have checked, the response is Unauthorized from the API.
The RestClient includes the authenticator with 
ConsumerKey
ConsumerSecret
Token
TokenSecret
Verifier

This should be all that is needed to authenticate and receive the token I believe.

```

 public BitBucketController()
        {
            sharpbucket = new SharpBucket.V1.SharpBucketV1();
            authenticator = sharpbucket.OAuth3LeggedAuthentication(BitbucketApiKey, BitbucketApiSecret, "oob");
        }

        public void GetPin()
        {
            var uri = authenticator.StartAuthentication();
            Process.Start(uri);
        }

        public void Authenticate(string pin)
        {
            authenticator.AuthenticateWithPin(pin);
        }
```

**Comment by techy2493** [comment]
I've done some digging.

AuthenticateWithPin calls SetAuthTokens.

SetAuthTokens is used both for Start Authentication and Authenticate with Pin.

However, SetAuthTokens has no way to identify which method to call.

I'm making SetAuthTokens take a string as a  method and passing the method path in at each request instead.

If you want I can add this as a pull request.

**Comment by MitjaBezensek** [comment]
Yes, that does seem to be the case, nice catch 👍 

The call from `StartAuthentication` should pass in `requestUrl` and the `AuthenticateWithPin` should pass in `accessUrl`. The constants are already defined in the class but I guess they are just not correctly passed.

I think that another thing that needs to be changed is that [here](https://github.com/MitjaBezensek/SharpBucket/blob/master/SharpBucket/Authentication/OAuthentication3Legged.cs#L34) the client that gets created does not have an `Authenticator' created for it. [Here](https://github.com/MitjaBezensek/SharpBucket/blob/master/SharpBucket/Authentication/OAuthentication2Legged.cs#L12) is how the code looks like for  `OAuthentication2Legged`, I guess that for the 3 legged version the created `Authenticator` should also receive the `OAuthToken` and `OAuthTokenSecret`.

It would be great if you could make these two changes into a PR. 

PS: Please note that I used a slightly different formatting than the traditional C# style in the project (starting curly brace is in the same line). So if you could please try to use this style, to keep the code consistent. Thanks.

**Comment by techy2493** [comment]
Sounds great.

I was just debugging the authentication client issues with a colleague and we reached the same conclusion.

I will fork this and make a pull request with the fixes ASAP.
