### ISSUE TITLE
Support for privately hosted bitbucket servers.

### ISSUE THREAD

**Issue by pauldotknopf** [MitjaBezensek/SharpBucket#48]

**Comment by MitjaBezensek** [comment]
Is there any documentation on BitBucket about how this can be done or if it is even supported? I [quickly searched here](https://confluence.atlassian.com/bitbucketserver/bitbucket-server-documentation-home-776639749.html) but couldn't find anything about it (they only mention webhooks).

**Comment by mongeon** [comment]
As far as I know, Hosted BitBucket server use the same API's. The authentication could be different (we use Basic authentication at work) 

https://developer.atlassian.com/bitbucket/server/docs/latest/how-tos/command-line-rest.html

We have used this SDK in the past: https://github.com/jlouros/StashApiCSharp

**Comment by MitjaBezensek** [comment]
@pauldotknopf @mongeon  Do you still need this functionality? I have some time to investigate this so I could add an optional parameter to the constructor that sets the base url. Then you could pass in the url to your local installation?

**Comment by mongeon** [comment]
Yes, I still have a need for that.

**Comment by MitjaBezensek** [comment]
@mongeon I'll take a look at this tomorrow. [Right now](https://github.com/MitjaBezensek/SharpBucket/blob/master/SharpBucket/V1/SharpBucketV1.cs#L10) there's a parameterless constructor, that just sets the `_baseUrl` to the default bitbucket API url. I guess just adding another constructor which accepts the local url would work for your case?

**Comment by MitjaBezensek** [comment]
I fixed this and it is available in the 0.7.0 version of the package. I just uploaded it to NuGet. Please try to download the package and let me know if it works.

**Comment by ffMathy** [comment]
I can't get it working anymore.
