### ISSUE TITLE
Allow customizing Base URL

### ISSUE THREAD

**Issue by ffMathy** [MitjaBezensek/SharpBucket#58]
Currently the wrapper can't be used for on-prem hosted Bitbucket solutions. Customizing the base URL would fix that.

**Comment by MitjaBezensek** [comment]
An issue for this already exists #48 . If you wish you can check out the PR #56 which allows the base URL override. Let me know if it works correctly.

**Comment by ffMathy** [comment]
I just did. Everything seems to be working okay.

**Comment by ffMathy** [comment]
I can't get it working anymore.
