### ISSUE TITLE
Add documentation for using with a local BitBucket server

### ISSUE THREAD

**Issue by MitjaBezensek** [MitjaBezensek/SharpBucket#61]
In the last version we added the ability to use SharpBucket with local BitBucket installation. Improve the documentation so that it shows a short example of the use.

**Comment by ffMathy** [comment]
I can't get it working anymore for some reason.

**Comment by ffMathy** [comment]
@MitjaBezensek any ideas?

**Comment by MitjaBezensek** [comment]
@ffMathy what exactly seems to be the problem? Do you get some exception? You can try to clone the repo and use the console program in the repo to try to access your local repo.

I can't test it out since I don't have a local installation.

**Comment by rupreck** [comment]
Actually the code seems wrong.  To access a local server and list the repositories using curl it requires.

curl -u userName:password9 -H "Content-Type: application/json" http://localhost:7990/rest/api/1.0/projects/

Use of the address incuding: "/rest/api/1.0/" is not found anywhere in the code so setting a base url of http://localhost:7990/ just never works.
