### ISSUE TITLE
Able to clone code based on tag?

### ISSUE THREAD

**Issue by spstratis** [MitjaBezensek/SharpBucket#75]
Not really an issue more of a question. I don't see any mention in the docs or the test apps about cloning the code in a repo, specifically cloning from a certain tag. Is this possible using this library?

**Comment by mnivet** [comment]
No it's not the intend of that library
cloning is a git operation
This library can help you to list the tags or commits that exists in a repository stored on BitBucket.
Then you may use that information to clone and checkout a selected tag, using git or potentially a C# implementation of git like [LibGit2Sharp](https://www.nuget.org/packages/LibGit2Sharp)
