### ISSUE TITLE
Commit summary

### ISSUE THREAD

**Issue by asherber** [MitjaBezensek/SharpBucket#82]
I'd like to add the summary for each commit. The JSON looks like this:

```json
"summary": {
    "raw": "[ABC-3392] a meaningful description\n",
    "markup": "markdown",
    "html": "<p>[<a rel=\"nofollow\" href=\"https://foo.atlassian.net/browse/ABC-3392\" target=\"_blank\" data-module-key=\"dvcs-connector-issue-key-linker\" data-link-key=\"dvcs-connector-issue-key-linker\" data-app-key=\"jira-bitbucket-connector-plugin.0277a6a4-4e3d-34e1-bab2-1c14de870122\" data-principal-uuid=\"{1b6feefd-32c1-4cb6-9e19-d662df20c277}\" class=\"ap-connect-dialog\">ABC-3392</a>] a meaningful description</p>",
    "type": "rendered"
},

```
In a local git repo, it's only the `raw` version that's useful; here the other fields show how BitBucket formats the summary for display -- in this case, it includes a link to the relevant issue in JIRA.

I'm happy to put together a PR, but should this property on `Commit` be a new `Summary` object, or should it just be a `string` with the `raw` value?

**Comment by asherber** [comment]
I figured that a `Summary` object is more in keeping with the design of the library, so I prepared a PR.

**Comment by mnivet** [comment]
Effectively, adding a `Summary` object was the best approach to respect the design of the library
