### ISSUE TITLE
TLS problem in SharpBucketTests

### ISSUE THREAD

**Issue by asherber** [MitjaBezensek/SharpBucket#84]
I ran into an issue running tests in the SharpBucketTests project. The project targets .NET 4.0, which by default does not enable TLS 1.2. Since Bitbucket has turned off support for TLS 1.0 and 1.1, the tests all fail with an error from RestSharp that a TLS connection could not be established.

The easiest fix would be to change the tests project to target .NET 4.6.2, which does have TLS 1.2 enabled. (SharpBucket itself could continue to target 4.0.)

Another option would be to add a `OneTimeSetup` method to `SampleRepositories` to explicitly enable current TLS versions, like so:

```csharp
[OneTimeSetUp]
public void OneTimeSetup()
{
    System.Net.ServicePointManager.SecurityProtocol =
        (SecurityProtocolType)3072     // TLS 1.2
        | (SecurityProtocolType)768    // TLS 1.1
        | SecurityProtocolType.Tls; 
}
```

**Comment by mnivet** [comment]
Yes it's an issue that I've also encountered but that didn't impact the CI of SharpBucket for an unknown reason.

However targeting NET 4.6.1 is enough and is what I planned to do to fix that issue and also be able to provide a far better unit test environment where we will build tests repositories using LibGit2Sharp.
That work is in the branch TestAPIThatAlterARepo that I expect to finish today

But I wait @MitjaBezensek to perform a small change on the CI environment so we can correctly use OAuth2 token and have the unit tests of that branch working in CI
