### ISSUE TITLE
v2 TeamProfile should be TeamInfo

### ISSUE THREAD

**Issue by 0x1mason** [MitjaBezensek/SharpBucket#9]
Looks to me like the properties for "TeamProfile" do not represent a team profile as described here: https://confluence.atlassian.com/display/BITBUCKET/teams+Endpoint#teamsEndpoint-GETtheteamprofile.

"TeamProfile" should probably be "TeamInfo", following the pattern in your other classes.

**Comment by MitjaBezensek** [comment]
Yeah, it seems that that part of the api is not implemented. The [GetProfile](https://github.com/MitjaBezensek/SharpBucket/blob/master/SharpBucket/V2/EndPoints/TeamsEndPoint.cs#L24) returns a [Team](https://github.com/MitjaBezensek/SharpBucket/blob/master/SharpBucket/V2/Pocos/Team.cs), which does not have the same fields as the example response.

I must admit I never used that part of the api, if you have more experience with it would you mind fixing this part?
