### ISSUE TITLE
SharpBucketV1 End of life

### ISSUE THREAD

**Issue by mnivet** [MitjaBezensek/SharpBucket#92]
As you know, the Version1 of Bitbucket Cloud API is deprecated and will be closed on 12 April 2019
https://confluence.atlassian.com/bitbucket/version-1-423626337.html

How should we managed that here ?
When should we start to drop the SharpBucketV1 class and all the code that is behind ?
* As soon as possible ?
* Or only after Bitbucket closed it ?

If I look at the current state of the developement of SharpBucket:
Release 0.7.2 Is the last one to have improved API V1 implementation (released in march)
Release 0.7.3 and all code already in master or in progress concern only API V2 implementation
So we can reasonably though that we won't maintain any more the API V1 implementation since nobody has shown any interest for that since months

In that context I suggest to tag the SharpBucketV1 class as obsolete for a next release. That release (0.8.0 if we are agree quickly ?) can be used by consumers to detect where they have code to change
Then in a next release (0.9.0 ?) we remove the class and all the code that is linked to API V1

Consumers that want to stay on the API V1 until the final date can stay on Release 0.7.3 (or on 0.8.0 with warnings), they are not forced to upgrade. So it should not stop us to stop supporting the API V1 before the final date.
Furthermore, at the final date our unit tests will break if we haven't drop the code before, which means that it would be better to drop that code not too late.

@MitjaBezensek, @asherber, are you agree with that strategy ?

**Comment by asherber** [comment]
I agree. It should be made clear to users that anyone who needs to keep support for V1 all the way until April (or needs it for local Bitbucket Server? I don't know how that works) should just stay on 0.7.3, which will not receive any further attention.

**Comment by MitjaBezensek** [comment]
Yes, I agree. Due to breaking changes next release will be 0.8.0 and we can also make the V1 obsolete. I'd still keep the code of V1 in until April. There's a small chance that someone might have a real need for a hotfix. They can fork the 0.7.3, but it doesn't really cost us anything to wait a few months before we drop it.

**Comment by mnivet** [comment]
Version 0.8.0 has been delivered so we can close that discussion
